### ISSUE TITLE
Way for single event subscription?

### ISSUE THREAD

**Issue by saschanaz** [WICG/observable#65]
I think this proposal is mostly for repeated events, but is there corresponding way of `once: true` in `addEventListener`?

Something like:

```js
await element.on("click").takeImmediately()
```

**Comment by benlesh** [comment]
This can be done like so:

```ts
await element.on('click').take(1).forEach(e => {
  // Do what you need do with the even in here.
  // Since this is synchronously dispatched, things like
  // e.preventDefault() can still be used.
});
```

**Comment by domfarolino** [comment]
At this point we've decided to add the `first()` Promise-returning operator (see https://github.com/WICG/observable/pull/131 and https://github.com/WICG/observable/issues/126) which I think satisfies this request, and @benlesh has kindly provided a nice example to keep synchronous scheduling when needing synchronously react to the "first" event (in order to `preventDefault()` or something like that).

I'll set up https://github.com/WICG/observable/pull/131 to close this issue once merged.
