### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by zloirock** [WICG/observable#79]
WPT tests is a great project, however, for a such concept as `Observable` it could be good to add a separate test suite for ensure compatibility user-land implementations with the standard.

For example, promises had [Promises/A+](https://github.com/promises-aplus/promises-tests) and [ES Promises](https://github.com/promises-es6/promises-es6) test suites.

The old TC39 `Observable` proposal also had [a test suite](https://github.com/tc39/proposal-observable/tree/master/es-observable-tests).

**Comment by domfarolino** [comment]
This could be interesting, but I don't think it is something for the standards community to maintain, probably. Separately, both of those repositories haven't been touched in 6-9 years respectively, which I imagine is by design, since those tests necessarily moved to the web platform level. Given that, if someone wants to start something up I wouldn't be opposed, but it feels like this venue is not the best place to discuss it.
