### ISSUE TITLE
Are IDL names like `Observer` too ambiguous?

### ISSUE THREAD

**Issue by keithamus** [WICG/observable#99]
Looking through the spec here, I see `Observer` is an IDL type but that might be a little ambiguous, as there are lots of "Observer" like things that exist across various specs, for example `ResizeObserver`, `MutationObserver` and so on.

This has practical ramifications, as [Webkit already has an Observer class](https://github.com/WebKit/WebKit/blob/main/Source/WTF/wtf/Observer.h), and [Firefox also has an Observer class](https://searchfox.org/mozilla-central/source/xpcom/ds/Observer.h) that are for different things. It would be useful to disambiguate against those, and it might be easier to simply rename this specifications `Observer` type.

Might I suggest a few alternative names:

 - `SubscriptionObserver`
 - `SubscriberLike` (my preference)
 - `ObservableSubscriber`
 - `SubscribeCallbacks`
 - `ObserverCallbacks`

**Comment by domfarolino** [comment]
Sure, I'm not opposed to renaming this in the spec. Ideally (and likely) other engines' Web IDL implementations have some sort of custom syntax to allow generic-named Web IDL interfaces/dictionaries to take on unique-named implementation name, as to prevent a _real_ conflict. Chromium has this, but yeah there's an argument even outside of that to rename this to be more specific.

Personally I'd like to stay away from using `Subscriber` in the name, since while there is a conceptual straight line you can draw between `Observer` and `Subscriber`, they are really not the same. Sticking with the precedent of `ResizeObserver`, `MutationObserver`, and so on, I'd prefer `SubscriptionObserver`. Do you want to make a PR?
